name: Auto Release (Full)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Semantic Release
        id: semrel
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Corepack
        if: steps.semrel.outputs.new_release_published == 'true'
        run: corepack enable

      - name: Install dependencies
        if: steps.semrel.outputs.new_release_published == 'true'
        run: pnpm i --frozen-lockfile

      - name: Build
        if: steps.semrel.outputs.new_release_published == 'true'
        run: pnpm build

      - name: Zip dist
        if: steps.semrel.outputs.new_release_published == 'true'
        run: zip -r woodll-tools-${{ steps.semrel.outputs.new_release_version }}.zip dist/*

      - name: Upload asset to release
        if: steps.semrel.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.semrel.outputs.new_release_version }}
          files: woodll-tools-${{ steps.semrel.outputs.new_release_version }}.zip
